input: ../data/bibliography_output.json
template: templates/bibliography.html.j2
output: ../docs/bibliography.html

template_dirs:
  - templates

context:
  title: "Bibliografia"
  page: "bibliography"
